import type { CategoryCard } from "./game";

export const DEFAULT_CATEGORY_CARDS: CategoryCard[] = [
  { easy: "Animales", medium: "Animales marinos", expert: "Animales que viven bajo tierra" },
  { easy: "Comidas", medium: "Postres", expert: "Ingredientes de la cocina asiática" },
  { easy: "Países", medium: "Ciudades europeas", expert: "Capitales africanas" },
  { easy: "Profesiones", medium: "Trabajos relacionados con el arte", expert: "Oficios desaparecidos" },
  { easy: "Objetos de una casa", medium: "Cosas de un baño", expert: "Objetos que funcionan sin electricidad" },
  { easy: "Deportes", medium: "Deportistas famosos", expert: "Disciplinas olímpicas de invierno" },
  { easy: "Películas", medium: "Películas de animación", expert: "Películas ganadoras del Óscar" },
  { easy: "Prendas de vestir", medium: "Accesorios", expert: "Materiales utilizados en moda" },
  { easy: "Cosas de una escuela", medium: "Asignaturas", expert: "Términos de geometría" },
  { easy: "Medios de transporte", medium: "Partes de un automóvil", expert: "Fabricantes de aviones" },
  { easy: "Frutas y verduras", medium: "Hierbas y especias", expert: "Alimentos fermentados" },
  { easy: "Personajes ficticios", medium: "Superhéroes", expert: "Villanos de la literatura" },
  { easy: "Cosas de una fiesta", medium: "Tipos de baile", expert: "Instrumentos de percusión" },
  { easy: "Lugares de una ciudad", medium: "Cosas de un aeropuerto", expert: "Elementos de arquitectura urbana" },
  { easy: "Partes del cuerpo", medium: "Especialidades médicas", expert: "Huesos del cuerpo humano" },
  { easy: "Colores", medium: "Piedras preciosas", expert: "Técnicas de pintura" },
  { easy: "Cosas frías", medium: "Fenómenos meteorológicos", expert: "Términos relacionados con glaciares" },
  { easy: "Cosas que hacen ruido", medium: "Sonidos de la naturaleza", expert: "Términos de acústica" },
  { easy: "Nombres propios", medium: "Personajes históricos", expert: "Filósofos y pensadores" },
  { easy: "Cosas redondas", medium: "Objetos de laboratorio", expert: "Inventos anteriores a 1900" },
  { easy: "Bebidas", medium: "Cócteles", expert: "Regiones vinícolas" },
  { easy: "Música", medium: "Grupos y bandas", expert: "Términos de teoría musical" },
  { easy: "Series de televisión", medium: "Personajes de comedia", expert: "Series ganadoras del Emmy" },
  { easy: "Libros", medium: "Autores latinoamericanos", expert: "Novelas publicadas antes de 1900" },
  { easy: "Plantas", medium: "Flores", expert: "Árboles nativos de América" },
  { easy: "Tecnología", medium: "Aplicaciones móviles", expert: "Lenguajes de programación" },
  { easy: "Internet", medium: "Redes sociales", expert: "Protocolos de internet" },
  { easy: "Viajes", medium: "Objetos de una maleta", expert: "Sitios Patrimonio de la Humanidad" },
  { easy: "Cosas de la playa", medium: "Deportes acuáticos", expert: "Términos de oceanografía" },
  { easy: "Cosas de la montaña", medium: "Equipo de senderismo", expert: "Accidentes geográficos" },
  { easy: "Utensilios de cocina", medium: "Técnicas de cocción", expert: "Técnicas de cocina francesa" },
  { easy: "Cosas de un restaurante", medium: "Platos italianos", expert: "Términos de alta cocina" },
  { easy: "Cosas de Navidad", medium: "Tradiciones de fin de año", expert: "Celebraciones de invierno" },
  { easy: "Disfraces", medium: "Cosas de Halloween", expert: "Criaturas mitológicas" },
  { easy: "Juegos de mesa", medium: "Juegos de cartas", expert: "Términos del ajedrez" },
  { easy: "Videojuegos", medium: "Personajes de videojuegos", expert: "Consolas antiguas" },
  { easy: "Juguetes", medium: "Juegos infantiles", expert: "Juguetes inventados antes de 1950" },
  { easy: "Mascotas", medium: "Razas de perros", expert: "Razas de gatos" },
  { easy: "Animales de granja", medium: "Herramientas agrícolas", expert: "Cultivos de clima templado" },
  { easy: "Animales de la selva", medium: "Plantas tropicales", expert: "Ecosistemas de selva" },
  { easy: "Cosas del océano", medium: "Peces", expert: "Especies de aguas profundas" },
  { easy: "Cosas del espacio", medium: "Planetas y lunas", expert: "Constelaciones" },
  { easy: "Ciencias", medium: "Científicos famosos", expert: "Ramas de la biología" },
  { easy: "Elementos químicos", medium: "Materiales de laboratorio", expert: "Compuestos químicos" },
  { easy: "Fuerzas y movimientos", medium: "Unidades de medida", expert: "Conceptos de física cuántica" },
  { easy: "Números", medium: "Figuras geométricas", expert: "Términos de estadística" },
  { easy: "Épocas históricas", medium: "Civilizaciones antiguas", expert: "Tratados históricos" },
  { easy: "Continentes y regiones", medium: "Ríos del mundo", expert: "Cordilleras" },
  { easy: "Idiomas", medium: "Palabras usadas en otros idiomas", expert: "Familias lingüísticas" },
  { easy: "Formas de comunicarse", medium: "Medios de comunicación", expert: "Términos de periodismo" },
  { easy: "Emociones", medium: "Maneras de demostrar cariño", expert: "Conceptos de psicología" },
  { easy: "Cosas que hacemos a diario", medium: "Verbos de movimiento", expert: "Acciones realizadas con las manos" },
  { easy: "Adjetivos positivos", medium: "Palabras para describir personas", expert: "Adjetivos relacionados con el carácter" },
  { easy: "Palabras cortas", medium: "Palabras con letras dobles", expert: "Palabras de origen griego" },
  { easy: "Unidades de tiempo", medium: "Cosas que duran menos de un minuto", expert: "Instrumentos para medir el tiempo" },
  { easy: "Tipos de clima", medium: "Cosas que usamos cuando llueve", expert: "Instrumentos meteorológicos" },
  { easy: "Estaciones del año", medium: "Actividades de verano", expert: "Fenómenos propios del invierno" },
  { easy: "Cosas de la mañana", medium: "Rutinas antes de salir", expert: "Trabajos que comienzan de madrugada" },
  { easy: "Cosas de la noche", medium: "Actividades nocturnas", expert: "Animales nocturnos" },
  { easy: "Lugares de trabajo", medium: "Herramientas de trabajo", expert: "Profesiones relacionadas con datos" },
  { easy: "Cosas de una oficina", medium: "Programas de oficina", expert: "Términos de recursos humanos" },
  { easy: "Empresas", medium: "Tipos de negocio", expert: "Términos de emprendimiento" },
  { easy: "Cosas que compramos", medium: "Formas de pago", expert: "Conceptos de economía" },
  { easy: "Tiendas", medium: "Cosas de un supermercado", expert: "Términos de comercio electrónico" },
  { easy: "Hábitos saludables", medium: "Tipos de ejercicio", expert: "Nutrientes esenciales" },
  { easy: "Cosas de un hospital", medium: "Instrumentos médicos", expert: "Pruebas diagnósticas" },
  { easy: "Productos de higiene", medium: "Cosas de una peluquería", expert: "Ingredientes cosméticos" },
  { easy: "Productos de belleza", medium: "Tipos de maquillaje", expert: "Tratamientos dermatológicos" },
  { easy: "Miembros de una familia", medium: "Actividades familiares", expert: "Términos de genealogía" },
  { easy: "Relaciones personales", medium: "Cualidades de un buen amigo", expert: "Formas de resolver conflictos" },
  { easy: "Cosas de bebés", medium: "Juegos para niños pequeños", expert: "Etapas del desarrollo infantil" },
  { easy: "Vacaciones", medium: "Destinos turísticos", expert: "Tipos de turismo" },
  { easy: "Cosas de un hotel", medium: "Servicios de hotel", expert: "Términos de hotelería" },
  { easy: "Cosas de un avión", medium: "Partes de un aeropuerto", expert: "Términos de navegación aérea" },
  { easy: "Marcas conocidas", medium: "Marcas de automóviles", expert: "Marcas fundadas antes de 1950" },
  { easy: "Personas famosas", medium: "Actores y actrices", expert: "Ganadores del Premio Nobel" },
  { easy: "Obras de arte", medium: "Artistas famosos", expert: "Movimientos artísticos" },
  { easy: "Edificios", medium: "Monumentos famosos", expert: "Estilos arquitectónicos" },
  { easy: "Elementos de la naturaleza", medium: "Parques nacionales", expert: "Reservas de la biosfera" },
  { easy: "Cultura latinoamericana", medium: "Platos latinoamericanos", expert: "Escritores latinoamericanos" },
];
